# site settings
title: Pass the SALT Conference
subtitle: Security and Libre Talks
email: contact@pass-the-salt.org
description: Dedicated to Free Software and Security. Since 2018.<br /><br> 3 days of talks &amp; workshops.<br> Free as in free beer and as in Freedom.<br>English spoken conference.<br><br> Lille, France | Polytech engineering school (<a href="https://goo.gl/maps/FusMa2F2GoP2">maps</a>).<br><br> > Current edition:&nbsp; <span style="display:inline-block;background-color:#d00063;"> <a href="https://2024.pass-the-salt.org/"> visit the 2024 edition website! </a></span> | Past:&nbsp; <a href="https://2023.pass-the-salt.org/">2023</a>, <a href="https://2022.pass-the-salt.org/">2022</a>, <a href="https://2021.pass-the-salt.org/">2021</a>, <a href="https://2020.pass-the-salt.org/">2020</a>, <a href="https://2019.pass-the-salt.org/">2019</a>, <a href="https://2018.pass-the-salt.org/">2018</a>.  
# baseurl: "/forty-jekyll-theme/" # the subpath of your site, e.g. /blog
url: https://www.pass-the-salt.org # the base hostname & protocol for your site
author:
street_address: Ecole Polytech, Avenue Paul Langevin
city: Villeneuve d'Ascq
zip_code: 59655 
country: France

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/passthesaltcon
twitter_account: passthesaltcon
mastodon_url: https://infosec.exchange/@passthesaltcon
mastodon_account: passthesaltcon
# build settings
markdown: kramdown 

sass:
  style: compressed
